using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace LinuxCore.Tests;

[TestClass]
public class LinuxErrorNumberTests
{
    [TestMethod]
    public void LinuxErrorNumber_Values_Match_Current_Platform_Headers()
    {
        NativeConstantAssert.EnumValuesMatch<LinuxErrorNumber>(
        [
            (nameof(LinuxErrorNumber.OK), "0"),
            (nameof(LinuxErrorNumber.OperationNotPermitted), "EPERM"),
            (nameof(LinuxErrorNumber.NoSuchFileOrDirectory), "ENOENT"),
            (nameof(LinuxErrorNumber.NoSuchProcess), "ESRCH"),
            (nameof(LinuxErrorNumber.InterruptedSystemCall), "EINTR"),
            (nameof(LinuxErrorNumber.InputOutputError), "EIO"),
            (nameof(LinuxErrorNumber.NoSuchDeviceOrAddress), "ENXIO"),
            (nameof(LinuxErrorNumber.ArgumentListTooLong), "E2BIG"),
            (nameof(LinuxErrorNumber.ExecFormatError), "ENOEXEC"),
            (nameof(LinuxErrorNumber.BadFileNumber), "EBADF"),
            (nameof(LinuxErrorNumber.NoChildProcesses), "ECHILD"),
            (nameof(LinuxErrorNumber.TryAgain), "EAGAIN"),
            (nameof(LinuxErrorNumber.OutOfMemory), "ENOMEM"),
            (nameof(LinuxErrorNumber.PermissionDenied), "EACCES"),
            (nameof(LinuxErrorNumber.BadAddress), "EFAULT"),
            (nameof(LinuxErrorNumber.BlockDeviceRequired), "ENOTBLK"),
            (nameof(LinuxErrorNumber.DeviceOrResourceBusy), "EBUSY"),
            (nameof(LinuxErrorNumber.FileExists), "EEXIST"),
            (nameof(LinuxErrorNumber.CrossDeviceLink), "EXDEV"),
            (nameof(LinuxErrorNumber.NoSuchDevice), "ENODEV"),
            (nameof(LinuxErrorNumber.NotADirectory), "ENOTDIR"),
            (nameof(LinuxErrorNumber.IsADirectory), "EISDIR"),
            (nameof(LinuxErrorNumber.InvalidArgument), "EINVAL"),
            (nameof(LinuxErrorNumber.FileTableOverflow), "ENFILE"),
            (nameof(LinuxErrorNumber.TooManyOpenFiles), "EMFILE"),
            (nameof(LinuxErrorNumber.NotATypewriter), "ENOTTY"),
            (nameof(LinuxErrorNumber.TextFileBusy), "ETXTBSY"),
            (nameof(LinuxErrorNumber.FileTooLarge), "EFBIG"),
            (nameof(LinuxErrorNumber.NoSpaceLeftOnDevice), "ENOSPC"),
            (nameof(LinuxErrorNumber.IllegalSeek), "ESPIPE"),
            (nameof(LinuxErrorNumber.ReadOnlyFileSystem), "EROFS"),
            (nameof(LinuxErrorNumber.TooManyLinks), "EMLINK"),
            (nameof(LinuxErrorNumber.BrokenPipe), "EPIPE"),
            (nameof(LinuxErrorNumber.MathArgOutOfDomain), "EDOM"),
            (nameof(LinuxErrorNumber.OutOfRange), "ERANGE"),
            (nameof(LinuxErrorNumber.ResourceDeadlockAvoided), "EDEADLK"),
            (nameof(LinuxErrorNumber.FileNameTooLong), "ENAMETOOLONG"),
            (nameof(LinuxErrorNumber.NoLocksAvailable), "ENOLCK"),
            (nameof(LinuxErrorNumber.InvalidSystemCall), "ENOSYS"),
            (nameof(LinuxErrorNumber.DirectoryNotEmpty), "ENOTEMPTY"),
            (nameof(LinuxErrorNumber.TooManySymbolicLinks), "ELOOP"),
            (nameof(LinuxErrorNumber.OperationWouldBlock), "EWOULDBLOCK"),
            (nameof(LinuxErrorNumber.NoMessageOfDesiredType), "ENOMSG"),
            (nameof(LinuxErrorNumber.IdentifierRemoved), "EIDRM"),
            (nameof(LinuxErrorNumber.ChannelNumberOutOfRange), "ECHRNG"),
            (nameof(LinuxErrorNumber.Level2NotSynchronized), "EL2NSYNC"),
            (nameof(LinuxErrorNumber.Level3Halted), "EL3HLT"),
            (nameof(LinuxErrorNumber.Level3Reset), "EL3RST"),
            (nameof(LinuxErrorNumber.LinkNumberOutOfRange), "ELNRNG"),
            (nameof(LinuxErrorNumber.ProtocolDriverNotAttached), "EUNATCH"),
            (nameof(LinuxErrorNumber.NoCSIChannel), "ENOCSI"),
            (nameof(LinuxErrorNumber.Level2Halted), "EL2HLT"),
            (nameof(LinuxErrorNumber.InvalidExchange), "EBADE"),
            (nameof(LinuxErrorNumber.InvalidRequestDescriptor), "EBADR"),
            (nameof(LinuxErrorNumber.ExchangeFull), "EXFULL"),
            (nameof(LinuxErrorNumber.NoAnode), "ENOANO"),
            (nameof(LinuxErrorNumber.InvalidRequestCode), "EBADRQC"),
            (nameof(LinuxErrorNumber.InvalidSlot), "EBADSLT"),
            (nameof(LinuxErrorNumber.SocketOperationOnNonSocket), "ENOTSOCK"),
            (nameof(LinuxErrorNumber.DestinationAddressRequired), "EDESTADDRREQ"),
            (nameof(LinuxErrorNumber.MessageTooLong), "EMSGSIZE"),
            (nameof(LinuxErrorNumber.ProtocolWrongTypeForSocket), "EPROTOTYPE"),
            (nameof(LinuxErrorNumber.ProtocolNotAvailable), "ENOPROTOOPT"),
            (nameof(LinuxErrorNumber.ProtocolNotSupported), "EPROTONOSUPPORT"),
            (nameof(LinuxErrorNumber.SocketTypeNotSupported), "ESOCKTNOSUPPORT"),
            (nameof(LinuxErrorNumber.OperationNotSupported), "EOPNOTSUPP"),
            (nameof(LinuxErrorNumber.ProtocolFamilyNotSupported), "EPFNOSUPPORT"),
            (nameof(LinuxErrorNumber.AddressFamilyNotSupported), "EAFNOSUPPORT"),
            (nameof(LinuxErrorNumber.AddressAlreadyInUse), "EADDRINUSE"),
            (nameof(LinuxErrorNumber.AddressNotAvailable), "EADDRNOTAVAIL"),
            (nameof(LinuxErrorNumber.NetworkIsDown), "ENETDOWN"),
            (nameof(LinuxErrorNumber.NetworkIsUnreachable), "ENETUNREACH"),
            (nameof(LinuxErrorNumber.NetworkReset), "ENETRESET"),
            (nameof(LinuxErrorNumber.ConnectionAborted), "ECONNABORTED"),
            (nameof(LinuxErrorNumber.ConnectionReset), "ECONNRESET"),
            (nameof(LinuxErrorNumber.NoBufferSpaceAvailable), "ENOBUFS"),
            (nameof(LinuxErrorNumber.AlreadyConnected), "EISCONN"),
            (nameof(LinuxErrorNumber.NotConnected), "ENOTCONN"),
            (nameof(LinuxErrorNumber.CannotSendAfterShutdown), "ESHUTDOWN"),
            (nameof(LinuxErrorNumber.TooManyReferences), "ETOOMANYREFS"),
            (nameof(LinuxErrorNumber.ConnectionTimedOut), "ETIMEDOUT"),
            (nameof(LinuxErrorNumber.ConnectionRefused), "ECONNREFUSED"),
            (nameof(LinuxErrorNumber.HostIsDown), "EHOSTDOWN"),
            (nameof(LinuxErrorNumber.NoRouteToHost), "EHOSTUNREACH"),
            (nameof(LinuxErrorNumber.OperationAlreadyInProgress), "EALREADY"),
            (nameof(LinuxErrorNumber.OperationNowInProgress), "EINPROGRESS")
        ], "errno.h");
    }
}